[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration files
# file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present.
# defaults to the current working directory.
# prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the filename.
# If specified, requires the python-dateutil library that can be
# found on PyPI
# timezone =

# max length of characters to apply to the
# "caveat" field when rendering the migration file
# max_cavelength = 40

# asset files
# version_path_separator = os.path.sep
# The version_path_separator, if set, will be applied to versions directory
# paths to separate the directory from the version, for a more human readable
#   path when generating documentation.
# version_path_separator = |

# The output encoding used when revision files are written from script.py
# outfile_encoding = utf-8

sqlalchemy.url = sqlite:///./infra_sim.db

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5s [%(asctime)s] %(name)s: %(message)s